# Generated by Django 4.2 on 2023-05-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='done',
            name='Age',
            field=models.IntegerField(default=''),
        ),
    ]
